package com.esparta.guru_02.mappers;

import com.esparta.guru_02.entities.Beer;
import com.esparta.guru_02.model.BeerCSVRecord;
import com.esparta.guru_02.model.BeerDTO;
import com.esparta.guru_02.model.BeerStyle;
import org.mapstruct.*;

import java.util.List;

/*
 * Author: M
 * Date: 28-Jan-26
 * Project Name: guru-02
 * Description: beExcellent
 *
 * BeerMapper
 *
 * Responsibility:
 * - Convert between Beer (JPA Entity) and BeerDTO (API / transport model)
 *
 * Design rules enforced here:
 * - DTOs NEVER control JPA-managed fields
 * - Entities remain managed by Hibernate
 * - Auditing and optimistic locking stay intact
 */
@Mapper(componentModel = "spring")
public interface BeerMapper {

    /* =========================================================
       DTO <-> ENTITY
       ========================================================= */

    BeerDTO beerToBeerDTO(Beer beer);

    List<BeerDTO> beerListToBeerDTOList(List<Beer> beers);

    @Mapping(target = "beerId", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "lastModifiedDate", ignore = true)
    @Mapping(target = "version", ignore = true)
    Beer beerDTOToBeer(BeerDTO dto);

    @Mapping(target = "beerId", ignore = true)
    @Mapping(target = "externalBeerId", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "lastModifiedDate", ignore = true)
    @Mapping(target = "version", ignore = true)
    void updateBeerFromDTO(BeerDTO dto, @MappingTarget Beer beer);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "externalBeerId", ignore = true)
    @Mapping(target = "beerId", ignore = true)
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "lastModifiedDate", ignore = true)
    @Mapping(target = "version", ignore = true)
    void patchBeerFromDTO(BeerDTO dto, @MappingTarget Beer beer);

    /* =========================================================
       CSV -> ENTITY
       ========================================================= */

    @Mapping(target = "beerId", ignore = true) // UUID generated by Hibernate
    @Mapping(target = "externalBeerId", source = "beerId")
    @Mapping(target = "beerName", source = "beer")
    @Mapping(target = "upc", expression = "java(generateUpc(record))")
    @Mapping(target = "quantityOnHand", constant = "0")
    @Mapping(target = "price", constant = "0.00")
    @Mapping(target = "createdDate", ignore = true)
    @Mapping(target = "lastModifiedDate", ignore = true)
    @Mapping(target = "version", ignore = true)
    Beer beerCSVRecordToBeer(BeerCSVRecord record);

    List<Beer> csvToBeerList(List<BeerCSVRecord> records);

    /* =========================================================
       HELPERS
       ========================================================= */

    default BeerStyle mapStyle(String style) {
        if (style == null) {
            return BeerStyle.IPA; // fallback
        }
        return BeerStyle.valueOf(style.toUpperCase().replace(" ", "_"));
    }

    default String generateUpc(BeerCSVRecord record) {
        // CSV does not provide UPC → generate deterministic one
        return "CSV-" + record.getBeerId();
    }
}